main/urls.py
from django.urls import path
import main.views as views


app_name = "main"
urlpatterns = [
	path("", views.index, name="index"),
	path("candidater/", views.candidater, name="candidater"),
]

technolab_student/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.


class Users(AbstractUser):
	pass

main/models.py
from django.db import models
from accounts.models import Users
from django.core.validators import RegexValidator


# Create your models here.


class Filiere(models.Model):
	nom = models.CharField(max_length=200)


class Cycle(models.Model):
	nom = models.CharField(max_length=200)
	nb_niveau = models.IntegerField(
		validators=[RegexValidator(regex=r'^(\d){1,3}$', message="Valeur non valide !")])

	def __str__(self):
		return self.nom


class Niveau(models.Model):
	cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
	programme = models.FileField(blank=True)


class Frais(models.Model):
	filiere = models.ForeignKey(Filiere, on_delete=models.SET_NULL, null=True)
	cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
	niveau = models.ForeignKey(Niveau, on_delete=models.CASCADE)
	montant = models.IntegerField(blank=True)


class Etudiant(Users):
	matricule = models.CharField(
		max_length=200, unique=True, blank=False, null=False,
		unique_for_year=True
		)
	nom = models.CharField(max_length=200)
	prenom = models.CharField(max_length=200)

	dir_files = "students_files/" + str(prenom) + "_" + str(nom) + "/"
	acte_naissance = models.FileField(
		upload_to=dir_files, verbose_name="Votre acte de  naissance"
	)
	attestation_bac = models.FileField(upload_to="students_files/")
	cycle = models.ForeignKey(Cycle, on_delete=models.CASCADE)
	filiere = models.ForeignKey(Filiere, on_delete=models.CASCADE)
	niveau = models.ForeignKey(Niveau, on_delete=models.CASCADE)
	frais = models.ForeignKey(Frais, on_delete=models.SET_DEFAULT, default=0, blank=True)

	class Meta:
		verbose_name = "Etudiant"
		verbose_name_plural = "Etudiants"

accounts/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
	return render(request, "main/index.html", {})


def candidater(request):
	return render(request, "main/candidature.html", {})

main/templates/main/base.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <link rel="stylesheet" href="{% static 'common/bootstrap/css/bootstrap.min.css' %}">
    {% block style %}{% endblock %}

    {% block script %}{% endblock %}
</head>
<body>
<header>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class=>
                <ul class="navbar-nav mr-auto align-items-center">
                    <li class="nav-item"><img src="{% static 'main/logo.png' %}" alt="logo du site"
                                              class="navbar-brand mt-0 h1"></li>
                    <li class="nav-item active">
                        <a href="{% url 'main:candidater' %}" class="nav-link">Candater</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Payer</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    {% block header %}{% endblock %}
</header>
{% block content %}{% endblock %}
{% block footer %}{% endblock %}
</body>
</html>

main/templates/main/candidature.html
{% extends "main/base.html" %}

{% block title %}Candidature Technolab{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-5 offset-md-1">
                <h1 class="text-info">Bienvenue sur la page de candidature !</h1>
            </div>
            <div class="col-md-5">
                <p class="text-warning h2">Merci de bien entrer les bonnes informations.</p>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}Technolab Student{% endblock %}

{% block style %}
    <style>
    </style>
{% endblock %}

{% block header %}{% endblock %}

{% block content %}
    <h1>Bienvenue Tachnolab !</h1>
{% endblock %}

{% block footer %}
    <div class="container">
        <div class="row text-center">
            <div class="col-3">
                <a href="https://wa.me/+22379376132/?text=Salut technolab...">whatsapp</a>
            </div>
            <div class="col-3">
                <a href="#">Conditions d'utilisations</a>
            </div>
            <div class="col-3">
                <a href="tel:+22379376132">+223 79 37 61 32</a>
            </div>
            <div class="col-3">
                <a href="mailto:mallemoussa091@gmail.com">Gmail</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12 text-center text-primary">
                <h1>(c) tous droits reservés - jouillet 2023</h1>
            </div>
        </div>
    </div>
{% endblock %}